/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_diegocruz;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dfcm9
 */
public class ExamenMain extends javax.swing.JFrame {
    
    
    
    Artista artistalogeado = null;
    
    Album albref = null;
    int contalbum = 0;
    ArrayList<Cancion> tempcanciones = new ArrayList();
    ArrayList<Artista> artis = new ArrayList();
    ArrayList<Cliente> clientes = new ArrayList();
    ArrayList<ListaRep> listasrep = new ArrayList();

    /**
     * Creates new form ExamenMain
     */
    public ExamenMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_crearcuenta = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombreu = new javax.swing.JTextField();
        js_edad = new javax.swing.JSpinner();
        cb_tipusuario = new javax.swing.JComboBox<>();
        jp_specialartist = new javax.swing.JPanel();
        tf_nomartistico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        jb_createacc = new javax.swing.JButton();
        JD_mainArtists = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_titulosingle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_fechasingle = new javax.swing.JTextField();
        jb_crearSingle = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tf_tituloalbum = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_fechalanzalbum = new javax.swing.JTextField();
        jb_pubalbum = new javax.swing.JButton();
        js_cantcancionesinalbum = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_lanzamientosartista = new javax.swing.JTree();
        JD_addCancion = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nomcanc = new javax.swing.JTextField();
        tf_duracioncanc = new javax.swing.JTextField();
        jb_crearCancion = new javax.swing.JButton();
        JD_addcancionalbum = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_nomcancalbum = new javax.swing.JTextField();
        tf_durcancalbum = new javax.swing.JTextField();
        jb_crearcanc_album = new javax.swing.JButton();
        JD_user = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jtp_user = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_cancpref = new javax.swing.JList<>();
        cb_candisp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        pb_cancion = new javax.swing.JProgressBar();
        cb_canarep = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jb_reproducir = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_unamelogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_passlogin = new javax.swing.JTextField();
        jb_ingresarsesion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Crear nueva cuenta");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Usuario");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre:");

        tf_nombreu.setBackground(new java.awt.Color(51, 51, 51));
        tf_nombreu.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_nombreu.setForeground(new java.awt.Color(255, 255, 255));

        js_edad.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        js_edad.setModel(new javax.swing.SpinnerNumberModel(12, 0, null, 1));

        cb_tipusuario.setBackground(new java.awt.Color(51, 51, 51));
        cb_tipusuario.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cb_tipusuario.setForeground(new java.awt.Color(255, 255, 255));
        cb_tipusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artista", "Cliente" }));
        cb_tipusuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipusuarioItemStateChanged(evt);
            }
        });

        jp_specialartist.setBackground(new java.awt.Color(0, 102, 51));
        jp_specialartist.setForeground(new java.awt.Color(0, 102, 51));

        tf_nomartistico.setBackground(new java.awt.Color(51, 51, 51));
        tf_nomartistico.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_nomartistico.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre Artistico:");

        javax.swing.GroupLayout jp_specialartistLayout = new javax.swing.GroupLayout(jp_specialartist);
        jp_specialartist.setLayout(jp_specialartistLayout);
        jp_specialartistLayout.setHorizontalGroup(
            jp_specialartistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_specialartistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_specialartistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_specialartistLayout.setVerticalGroup(
            jp_specialartistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_specialartistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomartistico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña:");

        tf_contra.setBackground(new java.awt.Color(51, 51, 51));
        tf_contra.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_contra.setForeground(new java.awt.Color(255, 255, 255));

        jb_createacc.setBackground(new java.awt.Color(51, 51, 51));
        jb_createacc.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_createacc.setForeground(new java.awt.Color(0, 153, 0));
        jb_createacc.setText("Crear Cuenta");
        jb_createacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_createaccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_specialartist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_createacc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addGap(427, 427, 427))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombreu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_specialartist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jb_createacc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_crearcuentaLayout = new javax.swing.GroupLayout(JD_crearcuenta.getContentPane());
        JD_crearcuenta.getContentPane().setLayout(JD_crearcuentaLayout);
        JD_crearcuentaLayout.setHorizontalGroup(
            JD_crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JD_crearcuentaLayout.setVerticalGroup(
            JD_crearcuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));
        jPanel3.setForeground(new java.awt.Color(0, 153, 51));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bienvenido Artista!");

        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 51));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Titulo:");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha de Lanzamiento:");

        jb_crearSingle.setBackground(new java.awt.Color(0, 102, 51));
        jb_crearSingle.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_crearSingle.setForeground(new java.awt.Color(255, 255, 255));
        jb_crearSingle.setText("Publicar");
        jb_crearSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearSingleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_fechasingle, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_titulosingle, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(jb_crearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_titulosingle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_fechasingle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jb_crearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Crear Single", jPanel4);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Titulo:");

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha de Lanzamiento:");

        jb_pubalbum.setBackground(new java.awt.Color(0, 102, 51));
        jb_pubalbum.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_pubalbum.setForeground(new java.awt.Color(255, 255, 255));
        jb_pubalbum.setText("Publicar");
        jb_pubalbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_pubalbumMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cantidad de Canciones");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_pubalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_fechalanzalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_tituloalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(217, 217, 217)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_cantcancionesinalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tituloalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_cantcancionesinalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_fechalanzalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jb_pubalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Crear Album", jPanel8);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar Single", jPanel6);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar Single", jPanel5);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albumes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Singles");
        treeNode1.add(treeNode2);
        jt_lanzamientosartista.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_lanzamientosartista);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Ver Lanzamientos", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_mainArtistsLayout = new javax.swing.GroupLayout(JD_mainArtists.getContentPane());
        JD_mainArtists.getContentPane().setLayout(JD_mainArtistsLayout);
        JD_mainArtistsLayout.setHorizontalGroup(
            JD_mainArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_mainArtistsLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JD_mainArtistsLayout.setVerticalGroup(
            JD_mainArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_mainArtistsLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 153, 0));

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Agregar Cancion");

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre:");

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Duracion (Segundos)");

        tf_nomcanc.setBackground(new java.awt.Color(102, 102, 102));
        tf_nomcanc.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_nomcanc.setForeground(new java.awt.Color(255, 255, 255));

        tf_duracioncanc.setBackground(new java.awt.Color(102, 102, 102));
        tf_duracioncanc.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_duracioncanc.setForeground(new java.awt.Color(255, 255, 255));

        jb_crearCancion.setBackground(new java.awt.Color(102, 102, 102));
        jb_crearCancion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_crearCancion.setForeground(new java.awt.Color(255, 255, 255));
        jb_crearCancion.setText("Crear Cancion");
        jb_crearCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCancionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_duracioncanc, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nomcanc, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jb_crearCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomcanc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_duracioncanc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jb_crearCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout JD_addCancionLayout = new javax.swing.GroupLayout(JD_addCancion.getContentPane());
        JD_addCancion.getContentPane().setLayout(JD_addCancionLayout);
        JD_addCancionLayout.setHorizontalGroup(
            JD_addCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_addCancionLayout.setVerticalGroup(
            JD_addCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(51, 153, 0));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Agregar Cancion");

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre:");

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Duracion (Segundos)");

        tf_nomcancalbum.setBackground(new java.awt.Color(102, 102, 102));
        tf_nomcancalbum.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_nomcancalbum.setForeground(new java.awt.Color(255, 255, 255));

        tf_durcancalbum.setBackground(new java.awt.Color(102, 102, 102));
        tf_durcancalbum.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tf_durcancalbum.setForeground(new java.awt.Color(255, 255, 255));

        jb_crearcanc_album.setBackground(new java.awt.Color(102, 102, 102));
        jb_crearcanc_album.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_crearcanc_album.setForeground(new java.awt.Color(255, 255, 255));
        jb_crearcanc_album.setText("Crear Cancion");
        jb_crearcanc_album.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearcanc_albumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_durcancalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nomcancalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jb_crearcanc_album, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nomcancalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_durcancalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jb_crearcanc_album, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout JD_addcancionalbumLayout = new javax.swing.GroupLayout(JD_addcancionalbum.getContentPane());
        JD_addcancionalbum.getContentPane().setLayout(JD_addcancionalbumLayout);
        JD_addcancionalbumLayout.setHorizontalGroup(
            JD_addcancionalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_addcancionalbumLayout.setVerticalGroup(
            JD_addcancionalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Bienvenido Cliente!");

        jtp_user.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtp_userStateChanged(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setForeground(new java.awt.Color(102, 102, 102));

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Listas de Reproduccion");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jtp_user.addTab("Listas de Reproduccion", jPanel12);

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane2.setViewportView(jl_cancpref);

        cb_candisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_candispActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar Cancion a la Lista");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Canciones Disponibles:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_candisp, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_candisp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        jtp_user.addTab("Lista de Canciones Preferidas", jPanel13);

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jtp_user.addTab("Cola de Reproduccion", jPanel14);

        jPanel15.setBackground(new java.awt.Color(102, 102, 102));

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Seleccione Cancion a Reproducir");

        jb_reproducir.setBackground(new java.awt.Color(0, 102, 204));
        jb_reproducir.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jb_reproducir.setForeground(new java.awt.Color(255, 255, 255));
        jb_reproducir.setText("Reproducir Cancion");
        jb_reproducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_reproducirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_canarep, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_canarep, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jb_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pb_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jtp_user.addTab("Reproducir Cancion", jPanel15);

        jLabel26.setText("jLabel26");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jtp_user.addTab("Agregar Lista", jPanel16);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jtp_user, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jtp_user, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_userLayout = new javax.swing.GroupLayout(JD_user.getContentPane());
        JD_user.getContentPane().setLayout(JD_userLayout);
        JD_userLayout.setHorizontalGroup(
            JD_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_userLayout.setVerticalGroup(
            JD_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Spotify");

        tf_unamelogin.setBackground(new java.awt.Color(102, 102, 102));
        tf_unamelogin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Contraseña");

        tf_passlogin.setBackground(new java.awt.Color(102, 102, 102));
        tf_passlogin.setForeground(new java.awt.Color(255, 255, 255));

        jb_ingresarsesion.setBackground(new java.awt.Color(0, 102, 51));
        jb_ingresarsesion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jb_ingresarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jb_ingresarsesion.setText("Ingresar Sesion");
        jb_ingresarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarsesionMouseClicked(evt);
            }
        });
        jb_ingresarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresarsesionActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Crear Cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_passlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(tf_unamelogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_ingresarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_unamelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_passlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jb_ingresarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ingresarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ingresarsesionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_tipusuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipusuarioItemStateChanged
        if (cb_tipusuario.getSelectedItem().toString().equals("Artista")){
            jp_specialartist.setVisible(true);
        }
        else{
            jp_specialartist.setVisible(false);
        }
    }//GEN-LAST:event_cb_tipusuarioItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JD_crearcuenta.pack();
        JD_crearcuenta.setModal(true);
        JD_crearcuenta.setLocationRelativeTo(this);
        JD_crearcuenta.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_createaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_createaccMouseClicked
        try {
            llenarartistas();
            llenarclientes();
            
            ArrayList <Usuario> temp = new ArrayList();
            
            temp.addAll(artis);
            temp.addAll(clientes);
            
            
            String uname, cont, nomart;
            int age;

            uname = tf_nombreu.getText();
            age = Integer.parseInt(js_edad.getValue().toString());
            cont = tf_contra.getText();
            nomart = tf_nomartistico.getText();

            
            if (cb_tipusuario.getSelectedItem().toString().equals("Artista")){
                
                if(age<18){
                    JOptionPane.showMessageDialog(null, "Lo siento usuario, debe ser mayor de 18 para ser artista.");
                }
                else{
                    boolean existe = false;
                    for (Usuario usuario : temp) {
                        
                        if (usuario.getUname().equals(tf_nombreu.getText())){
                            JOptionPane.showMessageDialog(null, "Este nombre de usuario ya existe!!");
                            existe = true;
                        }
                    }
                    
                    if (!existe){
                        Artista artx = new Artista(nomart, uname, cont, age);
                    
                        AdminArtistas aa = new AdminArtistas("./artists.dfc");
                        aa.cargarArchivo();
                        aa.setArtista(artx);
                        aa.escribirArchivo();

                        JOptionPane.showMessageDialog(null, "El artista ha sido creado exitosamente!");
                    }
                    
                }
            }
            else if (cb_tipusuario.getSelectedItem().toString().equals("Cliente")){
                if (age<12){
                    JOptionPane.showMessageDialog(null, "Lo siento usuario, debe ser mayor de 12 para ser cliente.");
                }
                else{
                    boolean existe = false;
                    for (Usuario usuario : temp) {
                        
                        if (usuario.getUname().equals(tf_nombreu.getText())){
                            JOptionPane.showMessageDialog(null, "Este nombre de usuario ya existe!!");
                            existe = true;
                        }
                    }
                    
                    if (!existe){
                        
                        Cliente y = new Cliente(uname, cont, age); 
                    
                        AdminClientes ac = new AdminClientes("./clients.dfc");
                        ac.cargarArchivo();
                        ac.setCliente(y);
                        ac.escribirArchivo();
                        
                        JOptionPane.showMessageDialog(null, "El cliente ha sido creado exitosamente!");

                    }
 
                }
                
                
            }
            

            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jb_createaccMouseClicked

    private void jb_ingresarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarsesionMouseClicked
        llenarartistas();
        llenarclientes();
        
        boolean sepudoellogin = false;
        
        for (Artista arti : artis) {
            
            if (arti.getUname().equals(tf_unamelogin.getText()) && arti.getPassw().equals(tf_passlogin.getText())){
                JOptionPane.showMessageDialog(null, "Usuario encontrado! Bienvenido Artista!");
                System.out.println(arti);
                artistalogeado = arti;
                JD_mainArtists.pack();
                JD_mainArtists.setModal(true);
                JD_mainArtists.setLocationRelativeTo(this);
                JD_mainArtists.setVisible(true);
                sepudoellogin = true;
                
            }

        }
        
        for (Cliente clin : clientes) {
            
            if (clin.getUname().equals(tf_unamelogin.getText()) && clin.getPassw().equals(tf_passlogin.getText())){
                JOptionPane.showMessageDialog(null, "Usuario encontrado! Bienvenido Cliente!");
                JD_user.pack();
                JD_user.setModal(true);
                JD_user.setLocationRelativeTo(this);
                JD_user.setVisible(true);
                sepudoellogin = true;
            }
            
        }
        
        if (!sepudoellogin){
            JOptionPane.showMessageDialog(null, "No se encontro un usuario con estas credenciales.");
        }
        
        
        
        
    }//GEN-LAST:event_jb_ingresarsesionMouseClicked

    private void jb_crearCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCancionMouseClicked
        
        
        File archivolanz = null;
        File archivocanc = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            String nomcan = tf_nomcanc.getText();
            int dur = Integer.parseInt(tf_duracioncanc.getText());
            String refsing = tf_titulosingle.getText();
            Cancion x = new Cancion(nomcan, dur, refsing);
            Single abc = new Single(x, tf_titulosingle.getText(), tf_fechasingle.getText());
            
            
            
            
            archivolanz = new File ("./lanzamientos.txt");
            fw = new FileWriter(archivolanz, true);
            bw = new BufferedWriter(fw);
            
            bw.write("Single, "+tf_titulosingle.getText()+", "+tf_fechasingle.getText()+", "+artistalogeado.getUname()+"\n");
            bw.flush();
            
            
            int mins = 0;
            int secs = dur;
            
            while (secs>=60) {      
                mins++;
                secs-=60;
                
            }
            
            archivocanc = new File("./canciones.txt");
            fw = new FileWriter(archivocanc, true);
            bw = new BufferedWriter(fw);
            
            bw.write(nomcan+", "+mins+":"+secs+", "+refsing+"\n");
            bw.flush();
            
            
            JOptionPane.showMessageDialog(null, "Cancion y Single creados exitosamente!");
            JD_addCancion.setVisible(false);
            tf_titulosingle.setText("");
            tf_fechasingle.setText("");
            tf_duracioncanc.setText("");
            tf_nomcanc.setText("");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jb_crearCancionMouseClicked

    private void jb_crearSingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearSingleMouseClicked
        JD_addCancion.pack();
        JD_addCancion.setModal(true);
        JD_addCancion.setLocationRelativeTo(this);
        JD_addCancion.setVisible(true);
        
    }//GEN-LAST:event_jb_crearSingleMouseClicked

    private void jb_pubalbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_pubalbumMouseClicked
        File archivolanz = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            
            String nomalb, fecalb;
            
            nomalb = tf_tituloalbum.getText();
            fecalb = tf_fechalanzalbum.getText();
            int cant = Integer.parseInt(js_cantcancionesinalbum.getValue().toString());
            
            Album x = new Album(cant, nomalb, fecalb);
            albref = x;
            
            archivolanz = new File ("./lanzamientos.txt");
            fw = new FileWriter(archivolanz, true);
            bw = new BufferedWriter(fw);
            
            bw.write("Album, "+tf_tituloalbum.getText()+", "+tf_fechalanzalbum.getText()+", "+artistalogeado.getUname()+"\n");
            bw.flush();
            
            contalbum = Integer.parseInt(js_cantcancionesinalbum.getValue().toString());
            JOptionPane.showMessageDialog(null, "Album Creado! Ahora procedera a agregar las canciones correspondientes.");
            JD_addcancionalbum.pack();
            JD_addcancionalbum.setModal(true);
            JD_addcancionalbum.setLocationRelativeTo(this);
            JD_addcancionalbum.setVisible(true);
            
            tempcanciones.clear();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jb_pubalbumMouseClicked

    private void jb_crearcanc_albumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearcanc_albumMouseClicked

        File archivocanc = null;
        FileWriter fw = null;
        BufferedWriter bw = null;

        try {
            
            
            String nomcan = tf_nomcancalbum.getText();
            int dur = Integer.parseInt(tf_durcancalbum.getText());
            String refalb = tf_tituloalbum.getText();
            Cancion ax = new Cancion(nomcan, dur, refalb);


            int mins = 0;
            int secs = dur;

            while (secs>=60) {      
                mins++;
                secs-=60;

            }

            archivocanc = new File("./canciones.txt");
            fw = new FileWriter(archivocanc, true);
            bw = new BufferedWriter(fw);

            bw.write(nomcan+", "+mins+":"+secs+", "+refalb+"\n");
            bw.flush();



            JOptionPane.showMessageDialog(null, "Cancion creada exitosamente!");
            albref.getCanciones().add(ax);
            contalbum--;
            tf_nomcancalbum.setText("");
            tf_durcancalbum.setText("");
            
            
            if (contalbum==0){
                JD_addcancionalbum.setVisible(false);
                tf_tituloalbum.setText("");
                tf_fechalanzalbum.setText("");
                
                
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_crearcanc_albumMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex()==4){
            try {
                llenarlanzamientos(artistalogeado);
            } catch (Exception ex) {
               ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cb_candispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_candispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_candispActionPerformed

    private void jtp_userStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtp_userStateChanged
        if (jtp_user.getSelectedIndex()==1){
            DefaultComboBoxModel modelobox = new DefaultComboBoxModel();
            ArrayList<Cancion> canciones = recorrercanciones();
            for (Cancion cancione : canciones) {
                modelobox.addElement(cancione);
            }
            cb_candisp.setModel(modelobox);
        }
        if (jtp_user.getSelectedIndex()==3){
            DefaultComboBoxModel modelobox = new DefaultComboBoxModel();
            ArrayList<Cancion> canciones = recorrercanciones();
            for (Cancion cancione : canciones) {
                modelobox.addElement(cancione);
            }
            cb_canarep.setModel(modelobox);
        }
    }//GEN-LAST:event_jtp_userStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel modellista = (DefaultListModel) jl_cancpref.getModel();
        modellista.addElement(cb_candisp.getSelectedItem());
        jl_cancpref.setModel(modellista);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_reproducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reproducirMouseClicked
        try {
            
            Cancion abc = (Cancion) cb_canarep.getSelectedItem();
            int dur = abc.getDuracion();
            ThreadCanc newrepro = new ThreadCanc(pb_cancion, dur);

            newrepro.start();
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jb_reproducirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenMain().setVisible(true);
            }
        });
    }
    
    
    public void llenarartistas(){
        artis.clear();
        AdminArtistas aa = new AdminArtistas("./artists.dfc");
        aa.cargarArchivo();
        artis.addAll(aa.getArtistas());
    }
    
    public void llenarclientes(){
        clientes.clear();
        AdminClientes ac = new AdminClientes("./clients.dfc");
        ac.cargarArchivo();
        clientes.addAll(ac.getClientes());
    }
    
    public void llenarListas(){
        listasrep.clear();
        AdminListaRep alr = new AdminListaRep("./listsrep.dfc");
        alr.cargarArchivo();
        listasrep.addAll(alr.getListasrep());
    }
    
    public void llenarlanzamientos(Artista x) throws FileNotFoundException{
        File archi = null;
        FileReader fr = null;
        BufferedReader br = null;
        ArrayList<Lanzamiento> temp = new ArrayList();
        DefaultTreeModel modelo = (DefaultTreeModel) jt_lanzamientosartista.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        ArrayList<Cancion> canstemp = recorrercanciones();
        
        System.out.println(canstemp);
        
        try {
            archi = new File("./lanzamientos.txt");
            fr = new FileReader(archi);
            br = new BufferedReader(fr);
            
            if (archi.exists()) {
                String linea = "";
                
                while ((linea = br.readLine()) != null) { 
                    
                    String [] infosplit = linea.split(",");
                    
                    String tipo = infosplit[0].trim();
                    String nomlanz = infosplit[1].trim();
                    String fechalanz = infosplit[2].trim();
                    String nomart = infosplit[3].trim();
                    
                    if (tipo.trim().equals("Single")){
                        Single ab = new Single(nomlanz, fechalanz);
                        if (nomart.equals(x.getUname())){
                            for (int i = 0; i < raiz.getChildCount(); i++) {
                                if (raiz.getChildAt(i).toString().equals("Singles")) {
                                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(ab);
                                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                                } 
                                
                            }
                        }
                        
                    }
                    else if (tipo.trim().equals("Album")){
                        Album df = new Album(nomlanz, fechalanz);
                        for (Cancion cancion : canstemp) {
                            if (cancion.getReflanz().equals(nomlanz)){
                                df.getCanciones().add(cancion);
                            }
                            
                        }
                        if (nomart.equals(x.getUname())){
                            for (int i = 0; i < raiz.getChildCount(); i++) {
                                if (raiz.getChildAt(i).toString().equals("Albumes")) {
                                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(df);
                                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                                } 
                                
                            }
                        }
                        
                    }
                    
                }

            }
            
            
            
            
            
            
        modelo.reload();   
        } catch (Exception e) {
        }
        
        
    }
    
    public ArrayList<Cancion> recorrercanciones(){
        
        
        System.out.println("Hola Amigos");
        ArrayList <Cancion> can= new ArrayList();
        File archi = null;
        FileReader fr = null;
        BufferedReader br = null;
        
        try {
            archi = new File("./canciones.txt");
            fr = new FileReader(archi);
            br = new BufferedReader(fr);
            
            if (archi.exists()) {
                String linea = "";
                
                while ((linea = br.readLine()) != null) { 
                    System.out.println(linea);
                    String [] infosplit = linea.split(",");
                    
                    String nomcan = infosplit[0].trim();
                    System.out.println(nomcan);
                    
                    String minssec = infosplit[1].trim();
                    System.out.println(minssec);
                    
                    
                    String referencia = infosplit[2].trim();
                    System.out.println(referencia);
                    
                    String [] minssec2 = minssec.split(":");
                    int minstosecs = Integer.parseInt(minssec2[0])*60;
                    int secs = Integer.parseInt(minssec2[1]);
                    
                    int dur = minstosecs+secs;
                    

                    Cancion abc = new Cancion(nomcan, dur, referencia);
                    can.add(abc);

                }
  
            }
            
            
        } catch (Exception e) {
        }
        
        System.out.println(can);
        return can;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_addCancion;
    private javax.swing.JDialog JD_addcancionalbum;
    private javax.swing.JDialog JD_crearcuenta;
    private javax.swing.JDialog JD_mainArtists;
    private javax.swing.JDialog JD_user;
    private javax.swing.JComboBox<String> cb_canarep;
    private javax.swing.JComboBox<String> cb_candisp;
    private javax.swing.JComboBox<String> cb_tipusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jb_crearCancion;
    private javax.swing.JButton jb_crearSingle;
    private javax.swing.JButton jb_crearcanc_album;
    private javax.swing.JButton jb_createacc;
    private javax.swing.JButton jb_ingresarsesion;
    private javax.swing.JButton jb_pubalbum;
    private javax.swing.JButton jb_reproducir;
    private javax.swing.JList<String> jl_cancpref;
    private javax.swing.JPanel jp_specialartist;
    private javax.swing.JSpinner js_cantcancionesinalbum;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JTree jt_lanzamientosartista;
    private javax.swing.JTabbedPane jtp_user;
    private javax.swing.JProgressBar pb_cancion;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_duracioncanc;
    private javax.swing.JTextField tf_durcancalbum;
    private javax.swing.JTextField tf_fechalanzalbum;
    private javax.swing.JTextField tf_fechasingle;
    private javax.swing.JTextField tf_nomartistico;
    private javax.swing.JTextField tf_nombreu;
    private javax.swing.JTextField tf_nomcanc;
    private javax.swing.JTextField tf_nomcancalbum;
    private javax.swing.JTextField tf_passlogin;
    private javax.swing.JTextField tf_tituloalbum;
    private javax.swing.JTextField tf_titulosingle;
    private javax.swing.JTextField tf_unamelogin;
    // End of variables declaration//GEN-END:variables

    /*
    
    if (jl_personas.getSelectedIndex () 
        >= 0) {
            DefaultTreeModel modeloARBOL
                = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        //obtener la persona a guardar
        DefaultListModel modeloLISTA
                = (DefaultListModel) jl_personas.getModel();
        
        String nacionalidad, nombre;
        int edad;        
        nacionalidad
                = ((Persona) modeloLISTA.get(
                        jl_personas.getSelectedIndex())).
                        getNacionalidad();
        
        nombre = ((Persona) modeloLISTA.get(
                jl_personas.getSelectedIndex())).
                getNombre();
        edad = ((Persona) modeloLISTA.get(
                jl_personas.getSelectedIndex())).
                getEdad();
        
        int centinela = -1;        
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().
                    equals(nacionalidad)) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Persona(nombre, edad, nacionalidad));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                centinela = 1;
            } //fin if
        } //fin for  
        
        if (centinela == -1) {
            DefaultMutableTreeNode n
                    = new DefaultMutableTreeNode(nacionalidad);
            DefaultMutableTreeNode p
                    = new DefaultMutableTreeNode(
                            new Persona(nombre, edad,
                                    nacionalidad)
                    );
            n.add(p);
            raiz.add(n);
        }  // fin if          
        
        
    }

    
        else {
            JOptionPane.showMessageDialog(this,
                "No hay persona seleccionada");
    }
    
}
    
    
    
    
    */
    
    
    
    


}
